export interface PrebuiltSensation {
  name: string;
  category: string;
  intensity: number;
  duration: string;
  cardType: "normal" | "wild" | "blackout";
}

export const SENSATION_CATEGORIES = [
  "Sensory",
  "Impact",
  "Bondage",
  "Teasing",
  "Service",
  "Roleplay",
  "Endurance",
  "Mind Games",
] as const;

export const PREBUILT_SENSATIONS: PrebuiltSensation[] = [
  // Sensory
  { name: "Blindfolded ice cube trail — neck to navel", category: "Sensory", intensity: 2, duration: "10 min", cardType: "normal" },
  { name: "Hot wax dripped on inner thighs", category: "Sensory", intensity: 4, duration: "15 min", cardType: "normal" },
  { name: "Feather tickle — bound and blindfolded", category: "Sensory", intensity: 2, duration: "10 min", cardType: "normal" },
  { name: "Wartenberg wheel from collarbone to hip", category: "Sensory", intensity: 3, duration: "10 min", cardType: "normal" },
  { name: "Temperature play — alternating hot towel and ice", category: "Sensory", intensity: 3, duration: "15 min", cardType: "normal" },
  { name: "Blindfolded taste test — sweet, sour, bitter, spicy", category: "Sensory", intensity: 1, duration: "10 min", cardType: "normal" },
  { name: "Scented oil massage with eyes covered", category: "Sensory", intensity: 1, duration: "20 min", cardType: "normal" },
  { name: "Electric play — violet wand teasing", category: "Sensory", intensity: 4, duration: "15 min", cardType: "normal" },
  { name: "Silk scarf dragged slowly across bare skin", category: "Sensory", intensity: 1, duration: "10 min", cardType: "normal" },
  { name: "Scratching with long nails — back, thighs, arms", category: "Sensory", intensity: 3, duration: "10 min", cardType: "normal" },
  { name: "Whispered commands with lips barely touching ear", category: "Sensory", intensity: 2, duration: "5 min", cardType: "normal" },
  { name: "Menthol balm on sensitive areas", category: "Sensory", intensity: 4, duration: "15 min", cardType: "normal" },
  { name: "Fur mitt stroke-down — head to toe", category: "Sensory", intensity: 1, duration: "10 min", cardType: "normal" },
  { name: "Sound deprivation — earplugs and blindfold combined", category: "Sensory", intensity: 3, duration: "20 min", cardType: "normal" },
  { name: "Cupping — suction cups on back and shoulders", category: "Sensory", intensity: 3, duration: "15 min", cardType: "normal" },
  { name: "Body writing — marker messages on skin", category: "Sensory", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Pinwheel roulette — spin to choose body zone", category: "Sensory", intensity: 3, duration: "10 min", cardType: "wild" },
  { name: "Sensation mystery box — Dom chooses tool blindly", category: "Sensory", intensity: 3, duration: "15 min", cardType: "wild" },

  // Impact
  { name: "Hand spanking — slow build from gentle to firm", category: "Impact", intensity: 3, duration: "10 min", cardType: "normal" },
  { name: "Paddle — 10 strikes, count each one aloud", category: "Impact", intensity: 4, duration: "5 min", cardType: "normal" },
  { name: "Flogger warm-up — thuddy, rhythmic strokes", category: "Impact", intensity: 2, duration: "10 min", cardType: "normal" },
  { name: "Riding crop — precise targeted strikes", category: "Impact", intensity: 4, duration: "10 min", cardType: "normal" },
  { name: "Belt folded double — 5 sharp strokes", category: "Impact", intensity: 5, duration: "5 min", cardType: "normal" },
  { name: "Cane — light tapping building to sting", category: "Impact", intensity: 5, duration: "10 min", cardType: "normal" },
  { name: "Thigh slapping — alternating sides", category: "Impact", intensity: 3, duration: "5 min", cardType: "normal" },
  { name: "Ruler on palms — school discipline roleplay", category: "Impact", intensity: 3, duration: "5 min", cardType: "normal" },
  { name: "Wooden spoon — kitchen discipline", category: "Impact", intensity: 4, duration: "5 min", cardType: "normal" },
  { name: "Face slapping — controlled, consensual", category: "Impact", intensity: 4, duration: "5 min", cardType: "normal" },
  { name: "Breast/chest slapping — light rhythmic taps", category: "Impact", intensity: 3, duration: "5 min", cardType: "normal" },
  { name: "Rubber band snapping — inner wrist or thigh", category: "Impact", intensity: 2, duration: "5 min", cardType: "normal" },
  { name: "Impact roulette — Dom picks tool, Sub picks count", category: "Impact", intensity: 4, duration: "10 min", cardType: "wild" },
  { name: "Mystery impact — Sub blindfolded, doesn't know what's coming", category: "Impact", intensity: 4, duration: "10 min", cardType: "blackout" },
  { name: "Stress position spanking — hands on wall, legs apart", category: "Impact", intensity: 4, duration: "10 min", cardType: "normal" },
  { name: "Rainbow spanking — mark every color from pink to red", category: "Impact", intensity: 5, duration: "15 min", cardType: "normal" },
  { name: "Warm-up then surprise — gentle massage ending in sharp smacks", category: "Impact", intensity: 3, duration: "10 min", cardType: "normal" },

  // Bondage
  { name: "Wrist tie — silk rope, arms above head", category: "Bondage", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Spread eagle — each limb tied to bedpost", category: "Bondage", intensity: 3, duration: "20 min", cardType: "normal" },
  { name: "Hogtie — wrists to ankles behind back", category: "Bondage", intensity: 4, duration: "15 min", cardType: "normal" },
  { name: "Shibari chest harness — decorative rope work", category: "Bondage", intensity: 3, duration: "30 min", cardType: "normal" },
  { name: "Collar and leash — led around the room", category: "Bondage", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Cling wrap mummification — torso only", category: "Bondage", intensity: 4, duration: "20 min", cardType: "normal" },
  { name: "Ankle cuffs — hobble walk training", category: "Bondage", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Predicament bondage — tied so movement causes sensation", category: "Bondage", intensity: 5, duration: "15 min", cardType: "normal" },
  { name: "Tape bondage — hands behind back with body tape", category: "Bondage", intensity: 3, duration: "15 min", cardType: "normal" },
  { name: "Suspension — partial, one limb elevated", category: "Bondage", intensity: 5, duration: "10 min", cardType: "normal" },
  { name: "Under-bed restraint system — full starfish", category: "Bondage", intensity: 3, duration: "20 min", cardType: "normal" },
  { name: "Rope dress — worn under clothing", category: "Bondage", intensity: 2, duration: "2 hours", cardType: "normal" },
  { name: "Bound meditation — tied comfortably and left to breathe", category: "Bondage", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Dom's choice restraint — surprise position", category: "Bondage", intensity: 3, duration: "20 min", cardType: "wild" },
  { name: "Mystery tie — blindfolded, don't know what's being bound", category: "Bondage", intensity: 3, duration: "15 min", cardType: "blackout" },
  { name: "Chair bondage — wrists and ankles to chair legs", category: "Bondage", intensity: 3, duration: "20 min", cardType: "normal" },
  { name: "Thumb cuffs — subtle restriction while doing tasks", category: "Bondage", intensity: 1, duration: "30 min", cardType: "normal" },

  // Teasing
  { name: "Edge 3 times — no release allowed", category: "Teasing", intensity: 4, duration: "20 min", cardType: "normal" },
  { name: "Lap dance for Dom — full performance, no touching", category: "Teasing", intensity: 2, duration: "5 min", cardType: "normal" },
  { name: "Strip poker — loser performs a dare", category: "Teasing", intensity: 2, duration: "30 min", cardType: "normal" },
  { name: "Slow undress — one piece every 5 minutes", category: "Teasing", intensity: 2, duration: "20 min", cardType: "normal" },
  { name: "Vibrator on lowest setting — worn during conversation", category: "Teasing", intensity: 3, duration: "15 min", cardType: "normal" },
  { name: "Read erotica aloud while being touched", category: "Teasing", intensity: 3, duration: "15 min", cardType: "normal" },
  { name: "Watch each other — no touching, 5 minutes", category: "Teasing", intensity: 2, duration: "5 min", cardType: "normal" },
  { name: "Send 5 explicit photos within 10 minutes", category: "Teasing", intensity: 2, duration: "10 min", cardType: "normal" },
  { name: "Dirty talk only — describe fantasy in detail", category: "Teasing", intensity: 2, duration: "10 min", cardType: "normal" },
  { name: "Orgasm denial — brought to edge then stopped", category: "Teasing", intensity: 5, duration: "20 min", cardType: "normal" },
  { name: "Countdown game — Dom counts from 10, Sub must hold still", category: "Teasing", intensity: 3, duration: "10 min", cardType: "normal" },
  { name: "Ice cube in mouth — kiss and trace body", category: "Teasing", intensity: 2, duration: "10 min", cardType: "normal" },
  { name: "Wear a plug — out to dinner", category: "Teasing", intensity: 3, duration: "2 hours", cardType: "normal" },
  { name: "No underwear rule — for the rest of the day", category: "Teasing", intensity: 1, duration: "rest of day", cardType: "normal" },
  { name: "Dom's teasing choice — anything goes", category: "Teasing", intensity: 3, duration: "15 min", cardType: "wild" },
  { name: "Mystery tease — blindfolded, unknown sensation", category: "Teasing", intensity: 3, duration: "15 min", cardType: "blackout" },
  { name: "Forced eye contact — maintain while being teased", category: "Teasing", intensity: 3, duration: "10 min", cardType: "normal" },
  { name: "Hands behind back — Dom teases, Sub can't touch", category: "Teasing", intensity: 3, duration: "15 min", cardType: "normal" },

  // Service
  { name: "Full body massage — 30 minutes, Dom's direction", category: "Service", intensity: 1, duration: "30 min", cardType: "normal" },
  { name: "Foot worship — wash, massage, kiss", category: "Service", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Draw a bath — with candles, music, everything perfect", category: "Service", intensity: 1, duration: "20 min", cardType: "normal" },
  { name: "Serve dinner on knees — present each course", category: "Service", intensity: 2, duration: "30 min", cardType: "normal" },
  { name: "Boot/shoe polishing — by hand, while kneeling", category: "Service", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Body grooming — shave Dom's chosen area", category: "Service", intensity: 2, duration: "20 min", cardType: "normal" },
  { name: "Personal valet — dress and undress Dom", category: "Service", intensity: 1, duration: "10 min", cardType: "normal" },
  { name: "Oral worship — on command, Dom's pace", category: "Service", intensity: 3, duration: "15 min", cardType: "normal" },
  { name: "Furniture service — act as footrest for 15 min", category: "Service", intensity: 3, duration: "15 min", cardType: "normal" },
  { name: "Hair brushing — 100 strokes, count aloud", category: "Service", intensity: 1, duration: "10 min", cardType: "normal" },
  { name: "Breakfast in bed — full service, presented kneeling", category: "Service", intensity: 1, duration: "30 min", cardType: "normal" },
  { name: "Wardrobe service — lay out Dom's outfit and accessories", category: "Service", intensity: 1, duration: "10 min", cardType: "normal" },
  { name: "Dom's choice service — surprise task assigned", category: "Service", intensity: 2, duration: "15 min", cardType: "wild" },
  { name: "Silent service — complete a task without speaking", category: "Service", intensity: 2, duration: "20 min", cardType: "normal" },
  { name: "Hand feeding — feed Dom grapes, chocolate, etc.", category: "Service", intensity: 1, duration: "15 min", cardType: "normal" },
  { name: "Nail painting — carefully, on knees", category: "Service", intensity: 1, duration: "20 min", cardType: "normal" },

  // Roleplay
  { name: "Interrogation scene — tied to chair, questions asked", category: "Roleplay", intensity: 3, duration: "20 min", cardType: "normal" },
  { name: "Teacher/student — pop quiz with consequences", category: "Roleplay", intensity: 2, duration: "20 min", cardType: "normal" },
  { name: "Boss/employee — performance review gone wrong", category: "Roleplay", intensity: 2, duration: "20 min", cardType: "normal" },
  { name: "Stranger at a bar — pretend to meet for the first time", category: "Roleplay", intensity: 2, duration: "30 min", cardType: "normal" },
  { name: "Doctor/patient — examination scene", category: "Roleplay", intensity: 3, duration: "20 min", cardType: "normal" },
  { name: "Royal court — kneel and petition for a favor", category: "Roleplay", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Photographer/model — pose on command", category: "Roleplay", intensity: 2, duration: "20 min", cardType: "normal" },
  { name: "Captor/captive — escape attempt scene", category: "Roleplay", intensity: 4, duration: "30 min", cardType: "normal" },
  { name: "Butler/maid — formal service with consequences for mistakes", category: "Roleplay", intensity: 2, duration: "30 min", cardType: "normal" },
  { name: "Auction — Dom describes Sub's 'features' to imaginary bidders", category: "Roleplay", intensity: 3, duration: "15 min", cardType: "normal" },
  { name: "Confession booth — admit desires, receive penance", category: "Roleplay", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Pet play — collar, leash, commands, treats for obedience", category: "Roleplay", intensity: 3, duration: "30 min", cardType: "normal" },
  { name: "Doll play — posed and positioned, must stay perfectly still", category: "Roleplay", intensity: 3, duration: "15 min", cardType: "normal" },
  { name: "Dom's fantasy — entire scene is Dom's choice", category: "Roleplay", intensity: 3, duration: "30 min", cardType: "wild" },
  { name: "Mystery scenario — Sub doesn't know the scene until it begins", category: "Roleplay", intensity: 3, duration: "20 min", cardType: "blackout" },
  { name: "Trainer/trainee — learn a new 'skill' with strict instruction", category: "Roleplay", intensity: 2, duration: "20 min", cardType: "normal" },

  // Endurance
  { name: "Hold stress position — hands on head, 5 minutes", category: "Endurance", intensity: 3, duration: "5 min", cardType: "normal" },
  { name: "Wall sit — hold until told to stop", category: "Endurance", intensity: 4, duration: "5 min", cardType: "normal" },
  { name: "Kneel on hard floor — no cushion, 10 minutes", category: "Endurance", intensity: 3, duration: "10 min", cardType: "normal" },
  { name: "Hold ice cube in each hand — don't drop", category: "Endurance", intensity: 3, duration: "5 min", cardType: "normal" },
  { name: "Silent challenge — no sounds while being stimulated", category: "Endurance", intensity: 4, duration: "10 min", cardType: "normal" },
  { name: "Balance a book on head — while performing tasks", category: "Endurance", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Hold a coin against the wall with nose", category: "Endurance", intensity: 2, duration: "5 min", cardType: "normal" },
  { name: "Plank position — Dom decides when to stop", category: "Endurance", intensity: 4, duration: "5 min", cardType: "normal" },
  { name: "Stay still while tickled — any movement adds time", category: "Endurance", intensity: 3, duration: "10 min", cardType: "normal" },
  { name: "Cold shower — 2 minutes, no flinching", category: "Endurance", intensity: 4, duration: "2 min", cardType: "normal" },
  { name: "Edge without finishing — 5 rounds", category: "Endurance", intensity: 5, duration: "30 min", cardType: "normal" },
  { name: "Wear clothespins — chosen locations, timed", category: "Endurance", intensity: 4, duration: "10 min", cardType: "normal" },
  { name: "No eye contact — entire evening, punishment for breaking", category: "Endurance", intensity: 2, duration: "2 hours", cardType: "normal" },
  { name: "Dom's endurance test — surprise challenge", category: "Endurance", intensity: 4, duration: "10 min", cardType: "wild" },
  { name: "Mystery endurance — you won't know until it starts", category: "Endurance", intensity: 4, duration: "10 min", cardType: "blackout" },
  { name: "Orgasm counting — must count out loud, lose count = restart", category: "Endurance", intensity: 4, duration: "20 min", cardType: "normal" },
  { name: "Statue game — freeze in position on command", category: "Endurance", intensity: 2, duration: "15 min", cardType: "normal" },

  // Mind Games
  { name: "Truth or dare — Dom always picks, 10 rounds", category: "Mind Games", intensity: 2, duration: "20 min", cardType: "normal" },
  { name: "Recite rules — any mistake earns punishment", category: "Mind Games", intensity: 2, duration: "10 min", cardType: "normal" },
  { name: "Confess a fantasy — in explicit detail", category: "Mind Games", intensity: 2, duration: "10 min", cardType: "normal" },
  { name: "Choose your punishment — pick between two options", category: "Mind Games", intensity: 3, duration: "varies", cardType: "normal" },
  { name: "Guessing game — guess what Dom is thinking, wrong = consequence", category: "Mind Games", intensity: 2, duration: "10 min", cardType: "normal" },
  { name: "Gratitude list — name 10 things you're grateful for about Dom", category: "Mind Games", intensity: 1, duration: "10 min", cardType: "normal" },
  { name: "Simon says — BDSM edition with escalating commands", category: "Mind Games", intensity: 3, duration: "15 min", cardType: "normal" },
  { name: "Write lines — 'I will obey' 50 times, neatly", category: "Mind Games", intensity: 1, duration: "20 min", cardType: "normal" },
  { name: "Yes or no game — must answer honestly, no hesitation", category: "Mind Games", intensity: 2, duration: "10 min", cardType: "normal" },
  { name: "Countdown anticipation — Dom counts down, something happens at zero", category: "Mind Games", intensity: 3, duration: "5 min", cardType: "normal" },
  { name: "Journaling on command — write your deepest desire right now", category: "Mind Games", intensity: 1, duration: "15 min", cardType: "normal" },
  { name: "May I? — must ask permission for everything for 1 hour", category: "Mind Games", intensity: 2, duration: "1 hour", cardType: "normal" },
  { name: "Compliment battle — say something you love about Dom, back and forth", category: "Mind Games", intensity: 1, duration: "10 min", cardType: "normal" },
  { name: "Dom's mind game — psychological play, Dom's choice", category: "Mind Games", intensity: 3, duration: "15 min", cardType: "wild" },
  { name: "Mystery challenge — you won't know until it's happening", category: "Mind Games", intensity: 3, duration: "15 min", cardType: "blackout" },
  { name: "Forbidden words — banned list for 1 hour, slip = consequence", category: "Mind Games", intensity: 2, duration: "1 hour", cardType: "normal" },
  { name: "Would you rather — Dom's edition, both options are spicy", category: "Mind Games", intensity: 2, duration: "15 min", cardType: "normal" },
  { name: "Beg for it — convince Dom you deserve a reward", category: "Mind Games", intensity: 2, duration: "5 min", cardType: "normal" },
];
