export interface PrebuiltStandingOrder {
  name: string;
  category: string;
  priority: string;
}

export const STANDING_ORDER_CATEGORIES = [
  "Behavior",
  "Dress Code",
  "Communication",
  "Service",
  "Protocol",
  "Posture",
  "Digital",
  "Domestic",
] as const;

export const PREBUILT_STANDING_ORDERS: PrebuiltStandingOrder[] = [
  { name: "Always address Dom with their preferred title", category: "Behavior", priority: "urgent" },
  { name: "Ask permission before sitting on furniture", category: "Behavior", priority: "high" },
  { name: "Eyes down when being addressed unless told otherwise", category: "Behavior", priority: "standard" },
  { name: "No swearing or crude language", category: "Behavior", priority: "standard" },
  { name: "Always say 'thank you' after receiving a task or punishment", category: "Behavior", priority: "high" },
  { name: "No interrupting when Dom is speaking", category: "Behavior", priority: "urgent" },
  { name: "Always wait for permission before eating", category: "Behavior", priority: "high" },
  { name: "No complaining — express concerns respectfully at designated times", category: "Behavior", priority: "standard" },
  { name: "Always hold doors open for Dom", category: "Behavior", priority: "standard" },
  { name: "Greet Dom properly when they arrive home", category: "Behavior", priority: "high" },
  { name: "Always walk behind or beside Dom, never ahead", category: "Behavior", priority: "standard" },
  { name: "Ask permission before leaving the room", category: "Behavior", priority: "high" },
  { name: "No eye rolling or sighing when given instructions", category: "Behavior", priority: "urgent" },
  { name: "Always accept corrections gracefully", category: "Behavior", priority: "high" },

  { name: "Wear collar at all times when at home", category: "Dress Code", priority: "urgent" },
  { name: "No underwear unless given explicit permission", category: "Dress Code", priority: "high" },
  { name: "Wear only Dom-approved outfits when going out", category: "Dress Code", priority: "high" },
  { name: "Always wear matching lingerie sets", category: "Dress Code", priority: "standard" },
  { name: "Hair must be styled in Dom's preferred way", category: "Dress Code", priority: "standard" },
  { name: "Nails must always be clean and manicured", category: "Dress Code", priority: "standard" },
  { name: "Wear ankle bracelet or day collar in public", category: "Dress Code", priority: "high" },
  { name: "Sleep naked unless told otherwise", category: "Dress Code", priority: "standard" },
  { name: "Wear specific color palette chosen by Dom", category: "Dress Code", priority: "low" },
  { name: "Always wear heels when Dom is present", category: "Dress Code", priority: "standard" },
  { name: "Keep body groomed to Dom's specifications", category: "Dress Code", priority: "high" },
  { name: "Wear plug under clothing when instructed", category: "Dress Code", priority: "high" },
  { name: "No makeup unless Dom approves the look", category: "Dress Code", priority: "standard" },
  { name: "Wear Dom's favorite perfume or scent daily", category: "Dress Code", priority: "low" },

  { name: "Send good morning text every day before 8am", category: "Communication", priority: "high" },
  { name: "Send goodnight text with a reflection on the day", category: "Communication", priority: "standard" },
  { name: "Respond to all messages within 15 minutes", category: "Communication", priority: "urgent" },
  { name: "Use proper titles in all texts and conversations", category: "Communication", priority: "high" },
  { name: "Send a photo when arriving at any new location", category: "Communication", priority: "standard" },
  { name: "Report meals — what and when — daily", category: "Communication", priority: "standard" },
  { name: "Ask permission before making plans with others", category: "Communication", priority: "high" },
  { name: "Daily check-in at noon with mood and status", category: "Communication", priority: "standard" },
  { name: "Always answer Dom's calls immediately", category: "Communication", priority: "urgent" },
  { name: "Send three things you're grateful for each evening", category: "Communication", priority: "low" },
  { name: "Report any rule violations immediately and honestly", category: "Communication", priority: "urgent" },
  { name: "Ask for permission before spending over a set amount", category: "Communication", priority: "high" },
  { name: "Never lie or withhold information from Dom", category: "Communication", priority: "urgent" },

  { name: "Prepare Dom's coffee or tea every morning", category: "Service", priority: "high" },
  { name: "Draw Dom's bath when they request it", category: "Service", priority: "standard" },
  { name: "Lay out Dom's clothes for the next day", category: "Service", priority: "standard" },
  { name: "Remove Dom's shoes when they arrive home", category: "Service", priority: "high" },
  { name: "Serve Dom's plate first at every meal", category: "Service", priority: "standard" },
  { name: "Keep Dom's water glass filled at all times", category: "Service", priority: "standard" },
  { name: "Massage Dom's feet for 10 minutes each evening", category: "Service", priority: "standard" },
  { name: "Run errands without being asked when supplies are low", category: "Service", priority: "low" },
  { name: "Pack Dom's bag or lunch when needed", category: "Service", priority: "standard" },
  { name: "Warm the car or prepare transport before Dom leaves", category: "Service", priority: "low" },
  { name: "Iron and press Dom's clothing weekly", category: "Service", priority: "standard" },
  { name: "Keep a fresh towel ready for Dom after showers", category: "Service", priority: "standard" },
  { name: "Prepare snacks and drinks during Dom's relaxation time", category: "Service", priority: "low" },

  { name: "Kneel when Dom enters the room", category: "Protocol", priority: "high" },
  { name: "Present yourself for inspection every morning", category: "Protocol", priority: "high" },
  { name: "Wait in designated position when Dom is expected home", category: "Protocol", priority: "standard" },
  { name: "Follow the greeting ritual at the front door", category: "Protocol", priority: "high" },
  { name: "Perform the bedtime protocol before sleep", category: "Protocol", priority: "standard" },
  { name: "Assume presentation position when commanded", category: "Protocol", priority: "high" },
  { name: "Recite daily affirmation or mantra each morning", category: "Protocol", priority: "standard" },
  { name: "Kiss Dom's hand as a greeting and farewell", category: "Protocol", priority: "standard" },
  { name: "Kneel at Dom's feet during movie or TV time", category: "Protocol", priority: "low" },
  { name: "Follow mealtime protocols — serve, wait, eat last", category: "Protocol", priority: "standard" },
  { name: "Perform end-of-day review ritual before bed", category: "Protocol", priority: "standard" },
  { name: "Stand when Dom enters or leaves a room", category: "Protocol", priority: "standard" },
  { name: "Follow the punishment acceptance protocol without hesitation", category: "Protocol", priority: "urgent" },
  { name: "Perform weekly recommitment ritual on Sundays", category: "Protocol", priority: "low" },

  { name: "Maintain straight posture at all times", category: "Posture", priority: "standard" },
  { name: "Sit with legs crossed or together — never spread", category: "Posture", priority: "standard" },
  { name: "Kneel with back straight and hands on thighs", category: "Posture", priority: "high" },
  { name: "Stand with hands clasped behind back when waiting", category: "Posture", priority: "standard" },
  { name: "No slouching on furniture — sit upright at all times", category: "Posture", priority: "standard" },
  { name: "Head bowed when receiving instructions", category: "Posture", priority: "standard" },
  { name: "Practice Nadu position for 10 minutes daily", category: "Posture", priority: "standard" },
  { name: "Maintain graceful movements — no rushing or stumbling", category: "Posture", priority: "low" },
  { name: "Sleep in Dom-designated position", category: "Posture", priority: "low" },
  { name: "Keep hands visible and still when not in use", category: "Posture", priority: "standard" },
  { name: "Walk heel-to-toe with measured, deliberate steps", category: "Posture", priority: "low" },
  { name: "Assume tower position when told to stand at attention", category: "Posture", priority: "standard" },
  { name: "Practice proper table posture during all meals", category: "Posture", priority: "standard" },

  { name: "No social media without permission", category: "Digital", priority: "high" },
  { name: "Screen time limited to Dom-set hours", category: "Digital", priority: "standard" },
  { name: "Phone must be unlocked and accessible to Dom at all times", category: "Digital", priority: "high" },
  { name: "No deleting messages, browsing history, or apps", category: "Digital", priority: "urgent" },
  { name: "Share location with Dom at all times", category: "Digital", priority: "high" },
  { name: "No private conversations with others without disclosure", category: "Digital", priority: "high" },
  { name: "Send screenshot of screen time report weekly", category: "Digital", priority: "standard" },
  { name: "No downloading new apps without permission", category: "Digital", priority: "standard" },
  { name: "Phone on silent during Dom's designated quiet hours", category: "Digital", priority: "standard" },
  { name: "No watching adult content without Dom's approval", category: "Digital", priority: "high" },
  { name: "All passwords shared with Dom", category: "Digital", priority: "high" },
  { name: "No gaming during restricted hours", category: "Digital", priority: "standard" },
  { name: "Daily journal entry submitted digitally by midnight", category: "Digital", priority: "standard" },

  { name: "Keep the bedroom clean and bed made daily", category: "Domestic", priority: "standard" },
  { name: "Do dishes immediately after every meal", category: "Domestic", priority: "standard" },
  { name: "Vacuum and mop floors twice weekly", category: "Domestic", priority: "standard" },
  { name: "Laundry done and folded same day — no piling up", category: "Domestic", priority: "standard" },
  { name: "Kitchen counters wiped down after every use", category: "Domestic", priority: "standard" },
  { name: "Bathroom cleaned and sanitized every other day", category: "Domestic", priority: "standard" },
  { name: "Trash taken out before it overflows — never wait to be told", category: "Domestic", priority: "standard" },
  { name: "Groceries stocked according to Dom's preferred list", category: "Domestic", priority: "low" },
  { name: "Fresh flowers or candles maintained in common areas", category: "Domestic", priority: "low" },
  { name: "Dom's workspace kept tidy and organized", category: "Domestic", priority: "standard" },
  { name: "All surfaces dusted weekly", category: "Domestic", priority: "low" },
  { name: "Pantry and fridge organized and labels facing forward", category: "Domestic", priority: "low" },
  { name: "Windows cleaned monthly", category: "Domestic", priority: "low" },
  { name: "Prepare the home environment before Dom arrives — lighting, music, temperature", category: "Domestic", priority: "standard" },
];
