export interface PrebuiltPunishment {
  name: string;
  category: string;
  duration: string;
}

export const PUNISHMENT_CATEGORIES = [
  "Denial",
  "Physical",
  "Bondage",
  "Mental",
  "Restriction",
  "Orgasm Control",
  "Humiliation",
  "Tedious Tasks",
] as const;

export const PREBUILT_PUNISHMENTS: PrebuiltPunishment[] = [
  // Denial Punishments
  { name: "Take away their collar", category: "Denial", duration: "1-3 days" },
  { name: "Withhold spankings they look forward to", category: "Denial", duration: "1 week" },
  { name: "Make them watch you pleasure yourself — no touching", category: "Denial", duration: "30 min" },
  { name: "Send them to bed without dinner", category: "Denial", duration: "1 evening" },
  { name: "Forbid any contact — no texts, calls, or seeing you", category: "Denial", duration: "1-3 days" },
  { name: "Have them fast for a day", category: "Denial", duration: "1 day" },
  { name: "Don't allow them to sleep for a night (be safe)", category: "Denial", duration: "1 night" },
  { name: "Revoke phone privileges", category: "Denial", duration: "1-3 days" },
  { name: "Take away computer privileges", category: "Denial", duration: "1-3 days" },
  { name: "Completely ignore their presence", category: "Denial", duration: "2-6 hours" },
  { name: "Don't allow them to sleep in the bed with you", category: "Denial", duration: "1-3 nights" },
  { name: "No sweet treats", category: "Denial", duration: "1 week" },

  // Physical Punishments
  { name: "Kneel on rice", category: "Physical", duration: "15-30 min" },
  { name: "Flogging session", category: "Physical", duration: "10-20 min" },
  { name: "Spanking — hand, strap, belt, or paddle", category: "Physical", duration: "10-15 min" },
  { name: "Wear nipple clamps for the day", category: "Physical", duration: "4-8 hours" },
  { name: "Hot wax dripping", category: "Physical", duration: "15-30 min" },
  { name: "Ice on private parts (use caution)", category: "Physical", duration: "5-10 min" },
  { name: "Wear electro-stimulation device", category: "Physical", duration: "1-4 hours" },
  { name: "Riding crop session", category: "Physical", duration: "10-20 min" },
  { name: "Cold showers only", category: "Physical", duration: "1 week" },
  { name: "Body hair waxing — pull slowly", category: "Physical", duration: "30 min" },
  { name: "Pinch nipples/sensitive areas", category: "Physical", duration: "5-10 min" },
  { name: "Wear a Yoni egg all day without dropping it", category: "Physical", duration: "8 hours" },
  { name: "Clothespins on strategic body parts", category: "Physical", duration: "15-30 min" },
  { name: "Eat only spicy foods", category: "Physical", duration: "1-3 days" },
  { name: "Hold a spice on their tongue (pepper, salt)", category: "Physical", duration: "2-5 min" },
  { name: "Foot whipping", category: "Physical", duration: "10 min" },
  { name: "Caning session", category: "Physical", duration: "10-15 min" },
  { name: "Ice bath", category: "Physical", duration: "5-10 min" },
  { name: "Walk on Legos barefoot", category: "Physical", duration: "5-10 min" },
  { name: "Stand on uncooked pasta barefoot", category: "Physical", duration: "10 min" },
  { name: "Figging (shaped ginger root)", category: "Physical", duration: "15-30 min" },
  { name: "Stuff every hole — gag, plug, dildo", category: "Physical", duration: "30 min - 2 hours" },

  // Bondage Punishments
  { name: "Tie to the bed — leave without company", category: "Bondage", duration: "1-4 hours" },
  { name: "Shackle to furniture (desk, table, chair)", category: "Bondage", duration: "1-4 hours" },
  { name: "Tie up and make them kneel", category: "Bondage", duration: "30 min - 1 hour" },
  { name: "Bondage tape wrap — remove slowly later", category: "Bondage", duration: "1-2 hours" },
  { name: "Hog-tied for the afternoon", category: "Bondage", duration: "1-3 hours" },
  { name: "Cage them for the day", category: "Bondage", duration: "2-8 hours" },
  { name: "Breast bondage", category: "Bondage", duration: "30 min - 1 hour" },
  { name: "Collar with restraints attached", category: "Bondage", duration: "2-6 hours" },
  { name: "Tied up with least favorite music playing", category: "Bondage", duration: "1-2 hours" },
  { name: "Ball gag or bar of soap in mouth", category: "Bondage", duration: "15-30 min" },
  { name: "Tied up, standing in front of window, naked", category: "Bondage", duration: "30 min" },
  { name: "Tied down spread eagle — tickled", category: "Bondage", duration: "30 min - 1 hour" },

  // Mental Punishments
  { name: "Hold a position without moving", category: "Mental", duration: "15-30 min" },
  { name: "Write an essay on why breaking the rule was wrong", category: "Mental", duration: "1-2 hours" },
  { name: "Forced to hold urine with plenty to drink", category: "Mental", duration: "1-3 hours" },
  { name: "Sensory deprivation — ear plugs or blindfold", category: "Mental", duration: "30 min - 2 hours" },
  { name: "Full sensory deprivation — eyes, ears, and soft gag in dark room", category: "Mental", duration: "30 min - 1 hour" },
  { name: "Read something they hate and submit a book report", category: "Mental", duration: "1-3 days" },
  { name: "Write an apology letter for breaking a rule", category: "Mental", duration: "30 min - 1 hour" },
  { name: "Receive a verbal lecture on your disappointment", category: "Mental", duration: "15-30 min" },
  { name: "Call another Dom/Mistress to set the punishment", category: "Mental", duration: "30 min" },
  { name: "Place in desired position — used as you please all day", category: "Mental", duration: "4-8 hours" },
  { name: "Degrading name — used in public too", category: "Mental", duration: "1-7 days" },
  { name: "Withhold all praise", category: "Mental", duration: "1-7 days" },
  { name: "Corner time — stand and reflect", category: "Mental", duration: "15-30 min" },
  { name: "Time-out chair", category: "Mental", duration: "15-30 min" },
  { name: "Scolding — express deep disappointment", category: "Mental", duration: "10-20 min" },
  { name: "Silent treatment — no attention whatsoever", category: "Mental", duration: "2-12 hours" },

  // Restriction Punishments
  { name: "Forbidden from favorite foods", category: "Restriction", duration: "1-7 days" },
  { name: "No furniture — including the bed", category: "Restriction", duration: "1-3 days" },
  { name: "No eye contact from Dom whatsoever", category: "Restriction", duration: "1-3 days" },
  { name: "Cannot touch Dom under any circumstances", category: "Restriction", duration: "1-7 days" },
  { name: "Must kneel at Dom's feet whenever Dom sits", category: "Restriction", duration: "1-3 days" },
  { name: "Must crawl on all fours", category: "Restriction", duration: "2-8 hours" },
  { name: "Collar and leash — no moving without leash control", category: "Restriction", duration: "2-8 hours" },
  { name: "Right to speak revoked completely", category: "Restriction", duration: "1-7 days" },
  { name: "Cannot pleasure Dom — teased by proximity", category: "Restriction", duration: "1-3 days" },
  { name: "Send to bed early", category: "Restriction", duration: "1-3 nights" },
  { name: "No coloring/hobby activities", category: "Restriction", duration: "1 week" },
  { name: "No video game time", category: "Restriction", duration: "1-7 days" },
  { name: "No cuddles", category: "Restriction", duration: "1-3 days" },
  { name: "Cancel a looked-forward-to outing", category: "Restriction", duration: "1 event" },
  { name: "Remove favorite blanket or comfort item", category: "Restriction", duration: "1-7 days" },

  // Orgasm Control Punishments
  { name: "Forbidden from touching themselves", category: "Orgasm Control", duration: "1-7 days" },
  { name: "Chastity cage — Dom keeps the key", category: "Orgasm Control", duration: "1-7 days" },
  { name: "Can only orgasm in Dom's presence", category: "Orgasm Control", duration: "Until released" },
  { name: "Edging — withhold orgasm repeatedly", category: "Orgasm Control", duration: "1-2 hours" },
  { name: "Forced orgasms until they can't continue", category: "Orgasm Control", duration: "30 min - 1 hour" },
  { name: "App-controlled toy teasing all day — no orgasm allowed", category: "Orgasm Control", duration: "8-12 hours" },
  { name: "Tied down and teased all day with no relief", category: "Orgasm Control", duration: "4-8 hours" },
  { name: "Ruined orgasm — bring to edge and stop immediately", category: "Orgasm Control", duration: "30 min" },
  { name: "Step-by-step instructed masturbation", category: "Orgasm Control", duration: "30 min - 1 hour" },
  { name: "Spooning naked while locked in chastity", category: "Orgasm Control", duration: "1-3 hours" },

  // Humiliation Punishments
  { name: "Eat every meal on the floor from a pet dish", category: "Humiliation", duration: "1-3 days" },
  { name: "Drink from a pet bowl", category: "Humiliation", duration: "1-3 days" },
  { name: "Turned into human furniture", category: "Humiliation", duration: "1-4 hours" },
  { name: "Lick shoes clean", category: "Humiliation", duration: "15-30 min" },
  { name: "Clean feet and toes with tongue", category: "Humiliation", duration: "15-30 min" },
  { name: "Write insults on their body with marker", category: "Humiliation", duration: "1-3 days" },
  { name: "Full doggy living — collar, leash, bowls, barking only", category: "Humiliation", duration: "4-12 hours" },
  { name: "Humiliating temporary tattoos", category: "Humiliation", duration: "1-3 days" },
  { name: "Naked servant for the day", category: "Humiliation", duration: "4-12 hours" },
  { name: "Housework wearing a lubed butt plug", category: "Humiliation", duration: "2-4 hours" },
  { name: "Bathroom door must stay open", category: "Humiliation", duration: "1-7 days" },
  { name: "Dog commands only — sit, stay, lie down", category: "Humiliation", duration: "2-8 hours" },
  { name: "Bathe, dry, and groom Dom", category: "Humiliation", duration: "30 min - 1 hour" },
  { name: "Wear a sign stating their rule infraction", category: "Humiliation", duration: "2-6 hours" },
  { name: "Public apology — on their knees", category: "Humiliation", duration: "5-10 min" },
  { name: "No underwear in public or at work", category: "Humiliation", duration: "1-3 days" },
  { name: "Wear embarrassing clothing in public", category: "Humiliation", duration: "2-6 hours" },
  { name: "Wear a costume out", category: "Humiliation", duration: "2-6 hours" },
  { name: "Diaper for the day", category: "Humiliation", duration: "4-12 hours" },
  { name: "Place in a diaper with pacifier — home and public", category: "Humiliation", duration: "4-12 hours" },

  // Tedious Task Punishments
  { name: "Hold a ping pong ball against the wall with nose", category: "Tedious Tasks", duration: "15-30 min" },
  { name: "Hold coins under each finger against the wall", category: "Tedious Tasks", duration: "15-30 min" },
  { name: "Stand with stacks of books on head", category: "Tedious Tasks", duration: "15-30 min" },
  { name: "Household chores they hate", category: "Tedious Tasks", duration: "1-3 hours" },
  { name: "Chores while bound (wrists, ankles, etc.)", category: "Tedious Tasks", duration: "1-3 hours" },
  { name: "Clean bathroom floor with a toothbrush", category: "Tedious Tasks", duration: "1-3 hours" },
  { name: "Clean car with a cotton swab", category: "Tedious Tasks", duration: "2-6 hours" },
  { name: "Write the broken rule 100-1000 times on paper", category: "Tedious Tasks", duration: "1-4 hours" },
  { name: "Count jars and bottles of coins", category: "Tedious Tasks", duration: "1-3 hours" },
  { name: "Move grains of rice between bowls using chopsticks", category: "Tedious Tasks", duration: "1-3 hours" },
  { name: "Count each grain of rice", category: "Tedious Tasks", duration: "2-6 hours" },
  { name: "Organize pantry in alphabetical order", category: "Tedious Tasks", duration: "1-2 hours" },
  { name: "Stand in one spot naked with AC turned up", category: "Tedious Tasks", duration: "30 min - 1 hour" },
  { name: "Send nude selfie every morning at 5am", category: "Tedious Tasks", duration: "1-7 days" },
  { name: "Fill in every O in a magazine with ink", category: "Tedious Tasks", duration: "1-3 hours" },
  { name: "Wash every piece of clothing Dom owns", category: "Tedious Tasks", duration: "4-8 hours" },
  { name: "Trim the lawn with scissors", category: "Tedious Tasks", duration: "4-12 hours" },
  { name: "Personal comfort duty — warm when cold, cool when hot", category: "Tedious Tasks", duration: "4-12 hours" },
  { name: "Cock-warming for an hour using any body part", category: "Tedious Tasks", duration: "1 hour" },
  { name: "Count every item in the home", category: "Tedious Tasks", duration: "4-12 hours" },
  { name: "Create apology letter using cut-out magazine letters", category: "Tedious Tasks", duration: "2-4 hours" },
  { name: "Vacuum entire home with a small hand vacuum", category: "Tedious Tasks", duration: "3-6 hours" },
  { name: "Iron every piece of clothing — socks, underwear, pajamas", category: "Tedious Tasks", duration: "3-6 hours" },
  { name: "Separate all clothing by color", category: "Tedious Tasks", duration: "1-2 hours" },
  { name: "Cover a pinhole in a water balloon using 1 finger", category: "Tedious Tasks", duration: "30 min - 1 hour" },
];
