export interface PrebuiltSceneScript {
  name: string;
  category: string;
  duration: string;
  intensity: number;
  steps: { phase: string; instruction: string; durationNote: string }[];
}

export const SCENE_SCRIPT_CATEGORIES = [
  "Bondage",
  "Impact",
  "Sensory",
  "Power Exchange",
  "Worship",
  "Discipline",
  "Edge Play",
  "Roleplay",
] as const;

export const PREBUILT_SCENE_SCRIPTS: PrebuiltSceneScript[] = [
  {
    name: "Classic Rope Evening",
    category: "Bondage",
    duration: "45-60 min",
    intensity: 5,
    steps: [
      { phase: "Preparation", instruction: "Lay out rope, scissors, and aftercare supplies. Sub undresses and kneels", durationNote: "5 min" },
      { phase: "Connection", instruction: "Dom places hands on sub's shoulders. 10 deep breaths together. Establish safe word", durationNote: "3 min" },
      { phase: "Arms", instruction: "Bind wrists in front with single column tie. Check circulation — two fingers under rope", durationNote: "5 min" },
      { phase: "Chest Harness", instruction: "Create chest harness with decorative wraps. Adjust tension for comfort and aesthetics", durationNote: "15 min" },
      { phase: "Sensation", instruction: "Run fingers along rope lines. Alternate gentle tugs with soft caresses along bound areas", durationNote: "10 min" },
      { phase: "Hold", instruction: "Sub holds position while Dom photographs or admires the work. Verbal praise throughout", durationNote: "5 min" },
      { phase: "Release", instruction: "Slowly untie in reverse order. Massage each area as it's freed. Check for marks", durationNote: "10 min" },
      { phase: "Aftercare", instruction: "Wrap in blanket. Water, chocolate, gentle touch. Discuss the experience", durationNote: "10 min" },
    ],
  },
  {
    name: "Impact Progression Scene",
    category: "Impact",
    duration: "30-45 min",
    intensity: 6,
    steps: [
      { phase: "Warm-Up", instruction: "Sub bends over designated surface. Dom begins with gentle hand spanking over clothing", durationNote: "5 min" },
      { phase: "Escalation 1", instruction: "Remove clothing. Continue hand spanking with increasing firmness. Check color and response", durationNote: "5 min" },
      { phase: "Implement 1", instruction: "Switch to leather paddle. Start light, build rhythm. 10 strokes per side alternating", durationNote: "5 min" },
      { phase: "Check-In", instruction: "Pause. Sub rates pain 1-10. Water if needed. Discuss color — green/yellow/red", durationNote: "2 min" },
      { phase: "Implement 2", instruction: "Switch to flogger. Rhythmic figure-eight pattern across back and thighs", durationNote: "8 min" },
      { phase: "Peak", instruction: "Finish with 10 harder strokes (sub counts each one). Final check-in on headspace", durationNote: "5 min" },
      { phase: "Cool Down", instruction: "Gentle rubbing of impacted areas. Soft flogger strokes to bring down intensity", durationNote: "5 min" },
      { phase: "Aftercare", instruction: "Apply arnica or lotion. Blanket, water, praise. Photo marks if sub consents", durationNote: "10 min" },
    ],
  },
  {
    name: "Sensory Deprivation Journey",
    category: "Sensory",
    duration: "40-50 min",
    intensity: 7,
    steps: [
      { phase: "Setup", instruction: "Prepare blindfold, noise-canceling headphones, various textures (silk, leather, feather, ice, warm oil)", durationNote: "5 min" },
      { phase: "Blindfold", instruction: "Apply blindfold gently. Hold hands for 60 seconds to establish trust. Breathing together", durationNote: "3 min" },
      { phase: "Sound Removal", instruction: "Place headphones with white noise or silence. Sub is now in full sensory deprivation", durationNote: "2 min" },
      { phase: "Light Touch", instruction: "Feather strokes across arms, neck, inner thighs. Unpredictable patterns", durationNote: "7 min" },
      { phase: "Temperature Play", instruction: "Alternate ice cube trails with warm oil drips. Focus on contrast and surprise", durationNote: "8 min" },
      { phase: "Texture Exploration", instruction: "Silk, leather, fur, rough fabric — drag across different body parts slowly", durationNote: "7 min" },
      { phase: "Stillness", instruction: "Stop all touch for 2 full minutes. Let anticipation build. Then one single touch", durationNote: "3 min" },
      { phase: "Gradual Return", instruction: "Remove headphones first. Whisper praise. Remove blindfold slowly in dim light", durationNote: "5 min" },
      { phase: "Aftercare", instruction: "Full body gentle massage. Water, warmth, debrief on what sensations stood out", durationNote: "10 min" },
    ],
  },
  {
    name: "Power Exchange Ceremony",
    category: "Power Exchange",
    duration: "30-40 min",
    intensity: 4,
    steps: [
      { phase: "Ritual Opening", instruction: "Light candles. Sub kneels. Dom stands. Both state their roles and commitment aloud", durationNote: "5 min" },
      { phase: "Collaring", instruction: "Dom presents collar. Sub bows head. Dom fastens collar and lifts sub's chin", durationNote: "3 min" },
      { phase: "Declarations", instruction: "Sub recites devotion pledge. Dom recites protection pledge. Exchange of words", durationNote: "5 min" },
      { phase: "Commands", instruction: "Dom gives 5 simple commands. Sub executes each with grace and verbal acknowledgment", durationNote: "5 min" },
      { phase: "Service Act", instruction: "Sub performs a chosen act of service — foot washing, massage, or drink preparation", durationNote: "10 min" },
      { phase: "Gratitude", instruction: "Both share 3 things they are grateful for in the dynamic. Honest, vulnerable exchange", durationNote: "5 min" },
      { phase: "Closing", instruction: "Dom cups sub's face and speaks final words of ownership and care. Kiss on forehead", durationNote: "5 min" },
    ],
  },
  {
    name: "Worship Session",
    category: "Worship",
    duration: "30-40 min",
    intensity: 3,
    steps: [
      { phase: "Preparation", instruction: "Sub prepares warm water basin, towel, and lotion. Kneels with supplies ready", durationNote: "5 min" },
      { phase: "Foot Washing", instruction: "Sub gently washes Dom's feet. Slow, reverent movements. Eye contact encouraged", durationNote: "8 min" },
      { phase: "Drying", instruction: "Pat dry with soft towel. Kiss each foot before and after drying", durationNote: "3 min" },
      { phase: "Massage", instruction: "Apply lotion with deep pressure massage. Focus on arches, heels, each toe individually", durationNote: "10 min" },
      { phase: "Verbal Worship", instruction: "While massaging, sub speaks about what they admire, respect, and love about their Dom", durationNote: "5 min" },
      { phase: "Gratitude", instruction: "Sub kisses each hand. Thanks Dom for allowing the act of worship", durationNote: "3 min" },
      { phase: "Aftercare", instruction: "Dom pulls sub up. Embrace. Verbal affirmation of how the worship was received", durationNote: "5 min" },
    ],
  },
  {
    name: "Discipline & Correction Scene",
    category: "Discipline",
    duration: "25-35 min",
    intensity: 6,
    steps: [
      { phase: "Summon", instruction: "Sub is called to stand before Dom. Hands at sides, eyes down. Wait in silence", durationNote: "2 min" },
      { phase: "Address", instruction: "Dom states the infraction clearly and specifically. Sub is not to speak until asked", durationNote: "3 min" },
      { phase: "Acknowledgment", instruction: "Sub repeats back the infraction and accepts responsibility. No excuses permitted", durationNote: "3 min" },
      { phase: "Consequence", instruction: "Dom administers pre-agreed consequence — corner time, writing lines, or impact", durationNote: "10 min" },
      { phase: "Reflection", instruction: "Sub writes or speaks a reflection on why the behavior was wrong and how to improve", durationNote: "5 min" },
      { phase: "Forgiveness", instruction: "Dom formally forgives. The matter is closed. Slate is clean", durationNote: "2 min" },
      { phase: "Reconnection", instruction: "Physical comfort — embrace, head on lap, gentle stroking. Reaffirm the bond", durationNote: "10 min" },
    ],
  },
  {
    name: "Wax Play Experience",
    category: "Edge Play",
    duration: "35-45 min",
    intensity: 7,
    steps: [
      { phase: "Preparation", instruction: "Lay down protective sheet. Test candle wax temperature on inner wrist. Sub positions face down", durationNote: "5 min" },
      { phase: "First Drops", instruction: "Begin with high-drip distance (18+ inches) on upper back. Gauge reaction", durationNote: "5 min" },
      { phase: "Closer Drips", instruction: "Lower candle gradually. Wax hits warmer. Drip along spine in decorative pattern", durationNote: "7 min" },
      { phase: "Expansion", instruction: "Expand to shoulders, lower back, buttocks. Alternate colors if using multiple candles", durationNote: "8 min" },
      { phase: "Intensity Peak", instruction: "Shorter drip distance for final area. Check in verbally. Praise endurance", durationNote: "5 min" },
      { phase: "Removal", instruction: "Peel wax slowly. Use a blunt edge to scrape gently. Reveal the marks beneath", durationNote: "5 min" },
      { phase: "Aftercare", instruction: "Apply soothing oil to all waxed areas. Warm blanket, water, debrief on sensations", durationNote: "10 min" },
    ],
  },
  {
    name: "Interrogation Roleplay",
    category: "Roleplay",
    duration: "30-45 min",
    intensity: 6,
    steps: [
      { phase: "Setup", instruction: "Sub is seated in a chair, optionally restrained. Room is dim with a single light source", durationNote: "5 min" },
      { phase: "Entrance", instruction: "Dom enters character — authority figure. Circles the chair slowly. Silence first", durationNote: "3 min" },
      { phase: "Questioning Round 1", instruction: "Simple questions about daily activities. Dom challenges every answer with skepticism", durationNote: "5 min" },
      { phase: "Pressure", instruction: "Increase intensity. Leaning close, lowered voice. Demand more detailed answers", durationNote: "5 min" },
      { phase: "Compliance Test", instruction: "Give a physical command — stand, turn around, hands on head. Assess compliance speed", durationNote: "5 min" },
      { phase: "Confession", instruction: "Ask sub to confess a real vulnerability or secret. Reward honesty with gentle touch", durationNote: "5 min" },
      { phase: "Resolution", instruction: "Break character. Hold sub close. Reaffirm that this was play and they are safe", durationNote: "5 min" },
      { phase: "Aftercare", instruction: "Extended comfort. Discussion about what felt good, what was intense. Reconnect fully", durationNote: "10 min" },
    ],
  },
  {
    name: "Pet Play Training Session",
    category: "Roleplay",
    duration: "30-40 min",
    intensity: 4,
    steps: [
      { phase: "Transformation", instruction: "Sub puts on ears/collar/tail. Gets on all fours. Dom attaches leash if desired", durationNote: "3 min" },
      { phase: "Basic Commands", instruction: "Sit, stay, come, heel. Practice each 3 times with treats as rewards", durationNote: "8 min" },
      { phase: "Fetch", instruction: "Toss a soft item. Sub retrieves on all fours and drops at Dom's feet", durationNote: "5 min" },
      { phase: "Affection", instruction: "Dom pets, scratches behind ears, belly rubs. Sub can nuzzle and purr/whimper", durationNote: "8 min" },
      { phase: "Feeding", instruction: "Dom hand-feeds treats or fruit. Sub eats gently from Dom's palm", durationNote: "5 min" },
      { phase: "Naptime", instruction: "Sub curls up at Dom's feet. Dom reads or relaxes while petting occasionally", durationNote: "5 min" },
      { phase: "Return", instruction: "Dom calls sub by real name. Remove accessories. Transition back with eye contact and embrace", durationNote: "5 min" },
    ],
  },
  {
    name: "Full Body Worship Marathon",
    category: "Worship",
    duration: "50-60 min",
    intensity: 4,
    steps: [
      { phase: "Opening", instruction: "Sub kneels. Dom sits or reclines. Sub asks permission to worship", durationNote: "2 min" },
      { phase: "Feet", instruction: "Kiss, massage, and worship each foot individually. Verbal adoration throughout", durationNote: "8 min" },
      { phase: "Legs", instruction: "Kiss and caress from ankles upward. Slow, attentive movements", durationNote: "8 min" },
      { phase: "Hands & Arms", instruction: "Kiss each fingertip. Massage palms. Kiss inner wrists and up the forearms", durationNote: "7 min" },
      { phase: "Shoulders & Neck", instruction: "Massage shoulders deeply. Gentle kisses along neck and collarbone", durationNote: "7 min" },
      { phase: "Face", instruction: "Gentle kisses on forehead, cheeks, nose, chin. Cup face with both hands", durationNote: "5 min" },
      { phase: "Verbal Culmination", instruction: "Sub gives a final spoken tribute — why they are devoted, what this means to them", durationNote: "5 min" },
      { phase: "Aftercare", instruction: "Dom holds sub. Both rest together. Gentle conversation about the experience", durationNote: "10 min" },
    ],
  },
  {
    name: "Predicament Bondage Challenge",
    category: "Bondage",
    duration: "25-35 min",
    intensity: 8,
    steps: [
      { phase: "Explanation", instruction: "Dom explains the predicament — two uncomfortable options, sub must choose which to endure", durationNote: "3 min" },
      { phase: "Setup", instruction: "Position sub in the predicament. Ensure safety measures are in place", durationNote: "5 min" },
      { phase: "Endurance Phase 1", instruction: "Sub holds position A for as long as possible. Dom observes and verbally encourages", durationNote: "5 min" },
      { phase: "Switch", instruction: "Sub switches to position B. Dom notes the transition and comments on endurance", durationNote: "5 min" },
      { phase: "Final Challenge", instruction: "Dom adds a third element — a sensation or task while maintaining the predicament", durationNote: "5 min" },
      { phase: "Release", instruction: "Free sub from predicament. Gentle massage of all stressed areas", durationNote: "5 min" },
      { phase: "Aftercare", instruction: "Praise endurance. Water, blanket, gentle physical comfort. Discuss the mental experience", durationNote: "10 min" },
    ],
  },
  {
    name: "Guided Subspace Journey",
    category: "Sensory",
    duration: "45-60 min",
    intensity: 5,
    steps: [
      { phase: "Environment", instruction: "Dim lights to near darkness. Soft ambient music. Warm room. Comfortable surface", durationNote: "3 min" },
      { phase: "Breathing", instruction: "Guide sub through box breathing — 4 counts in, hold, out, hold. 10 cycles", durationNote: "5 min" },
      { phase: "Progressive Relaxation", instruction: "Talk sub through relaxing each body part from toes to head. Slow, hypnotic voice", durationNote: "8 min" },
      { phase: "Light Sensation", instruction: "Begin very gentle touch — fingertips barely grazing skin. Unpredictable, flowing patterns", durationNote: "10 min" },
      { phase: "Deepening", instruction: "Increase touch pressure slowly. Incorporate rhythmic elements — tapping, stroking patterns", durationNote: "10 min" },
      { phase: "Peak", instruction: "Maintain the rhythm that produces the deepest response. Watch for signs of subspace", durationNote: "10 min" },
      { phase: "Return", instruction: "Slowly decrease stimulation. Gently call sub's name. Count up from 1 to 5 to return", durationNote: "5 min" },
      { phase: "Aftercare", instruction: "Extended holding. Warm drink. Do not rush. Sub may be disoriented — stay close and attentive", durationNote: "15 min" },
    ],
  },
  {
    name: "Black Protocol Enforcement",
    category: "Edge Play",
    duration: "45-60 min",
    intensity: 9,
    steps: [
      { phase: "Briefing", instruction: "Review hard limits, stop signals, and escalation caps. Confirm consent verbally and in writing", durationNote: "5 min" },
      { phase: "Command Lock", instruction: "Sub enters strict posture and silence. Dom sets cadence: command, compliance, reset", durationNote: "8 min" },
      { phase: "Discipline Cycle", instruction: "Run alternating drills: posture holds, impact sets, and response-time tests", durationNote: "15 min" },
      { phase: "Accountability", instruction: "Sub states each mistake precisely and requests corrective command", durationNote: "7 min" },
      { phase: "Peak Protocol", instruction: "Final controlled intensity block with continuous monitoring and timed check-ins", durationNote: "8 min" },
      { phase: "Release", instruction: "Dom clearly ends protocol, removes restraints, and slows breathing together", durationNote: "4 min" },
      { phase: "Aftercare", instruction: "Hydration, warmth, reassurance, and structured debrief before any follow-up tasks", durationNote: "12 min" },
    ],
  },
];