export interface PrebuiltReward {
  name: string;
  category: string;
  duration: string;
}

export const REWARD_CATEGORIES = [
  "Pleasure",
  "Freedom",
  "Pampering",
  "Quality Time",
  "Gifts & Treats",
  "Power Exchange",
  "Sensory",
  "Intimacy",
] as const;

export const PREBUILT_REWARDS: PrebuiltReward[] = [
  // Pleasure Rewards
  { name: "Extended massage — full body, their choice of oil", category: "Pleasure", duration: "45-60 min" },
  { name: "Oral pleasure session — no reciprocation required", category: "Pleasure", duration: "30 min" },
  { name: "Use of their favorite toy during play", category: "Pleasure", duration: "1 session" },
  { name: "Orgasm on demand — granted immediately when asked", category: "Pleasure", duration: "1 day" },
  { name: "Multiple orgasm session — no limits", category: "Pleasure", duration: "1 session" },
  { name: "Dom worships their body", category: "Pleasure", duration: "30-60 min" },
  { name: "Edging session with guaranteed finish", category: "Pleasure", duration: "45 min" },
  { name: "Choose the position for the night", category: "Pleasure", duration: "1 session" },
  { name: "Slow, sensual lovemaking — sub sets the pace", category: "Pleasure", duration: "1 session" },
  { name: "Fantasy fulfillment — one pre-discussed fantasy acted out", category: "Pleasure", duration: "1 session" },
  { name: "Vibrator privileges restored/upgraded", category: "Pleasure", duration: "1 week" },
  { name: "Wake-up pleasure — oral or touch to start the day", category: "Pleasure", duration: "1 morning" },
  { name: "Blindfolded pleasure — all sensation, no anticipation stress", category: "Pleasure", duration: "30-45 min" },
  { name: "Dom reads erotica aloud during play", category: "Pleasure", duration: "30 min" },
  { name: "Extended foreplay — minimum 1 hour before anything else", category: "Pleasure", duration: "1+ hours" },
  { name: "Pleasure without any rules or protocols", category: "Pleasure", duration: "1 evening" },
  { name: "Tantric breathing and connection session", category: "Pleasure", duration: "45 min" },
  { name: "After-play cuddling with no time limit", category: "Pleasure", duration: "Unlimited" },

  // Freedom Rewards
  { name: "Free day — no tasks, rules, or protocols", category: "Freedom", duration: "1 day" },
  { name: "Sleep in — no morning rituals or wake-up tasks", category: "Freedom", duration: "1 morning" },
  { name: "Choose what to watch/listen to for the evening", category: "Freedom", duration: "1 evening" },
  { name: "Phone/social media privileges restored", category: "Freedom", duration: "1-3 days" },
  { name: "Skip one task of their choosing", category: "Freedom", duration: "1 use" },
  { name: "Extended bedtime — stay up as late as they want", category: "Freedom", duration: "1 night" },
  { name: "No honorifics required for the day", category: "Freedom", duration: "1 day" },
  { name: "Wear whatever they want — no dress code", category: "Freedom", duration: "1 day" },
  { name: "Go out with friends — no check-in required", category: "Freedom", duration: "1 outing" },
  { name: "Eat whatever they want — no dietary restrictions", category: "Freedom", duration: "1 day" },
  { name: "Personal hobby time — uninterrupted", category: "Freedom", duration: "2-4 hours" },
  { name: "Skip workout/exercise for the day", category: "Freedom", duration: "1 day" },
  { name: "Choose the restaurant or meal", category: "Freedom", duration: "1 meal" },
  { name: "Lazy morning together — no responsibilities", category: "Freedom", duration: "1 morning" },
  { name: "Gaming or screen time without limits", category: "Freedom", duration: "1 evening" },
  { name: "Veto one punishment — use anytime", category: "Freedom", duration: "1 use" },
  { name: "Break one standing order for the day", category: "Freedom", duration: "1 day" },
  { name: "No kneeling or position requirements", category: "Freedom", duration: "1 day" },

  // Pampering Rewards
  { name: "Bubble bath drawn and prepared by Dom", category: "Pampering", duration: "45-60 min" },
  { name: "Dom does their chores for the day", category: "Pampering", duration: "1 day" },
  { name: "Breakfast in bed", category: "Pampering", duration: "1 morning" },
  { name: "Full spa treatment — face mask, scrub, oils", category: "Pampering", duration: "1-2 hours" },
  { name: "Hair brushing and styling session", category: "Pampering", duration: "30 min" },
  { name: "Foot rub or foot spa", category: "Pampering", duration: "30 min" },
  { name: "Dom cooks their favorite meal", category: "Pampering", duration: "1 evening" },
  { name: "Shopping trip — Dom carries everything", category: "Pampering", duration: "2-4 hours" },
  { name: "Nail painting/manicure session", category: "Pampering", duration: "30-45 min" },
  { name: "Candlelit dinner prepared by Dom", category: "Pampering", duration: "1 evening" },
  { name: "Dom cleans the entire house", category: "Pampering", duration: "1 day" },
  { name: "Warm towel and lotion after shower", category: "Pampering", duration: "15 min" },
  { name: "Dom washes their hair gently", category: "Pampering", duration: "20 min" },
  { name: "Aromatherapy diffuser set to their favorite scent", category: "Pampering", duration: "1 evening" },
  { name: "Fresh flowers delivered or arranged", category: "Pampering", duration: "Instant" },
  { name: "Heated blanket and comfort setup on the couch", category: "Pampering", duration: "1 evening" },
  { name: "Dom reads to them until they fall asleep", category: "Pampering", duration: "Until asleep" },

  // Quality Time Rewards
  { name: "Date night — sub chooses the plan", category: "Quality Time", duration: "1 evening" },
  { name: "Movie marathon — sub picks all the movies", category: "Quality Time", duration: "Half day" },
  { name: "Stargazing together with blankets and snacks", category: "Quality Time", duration: "1-2 hours" },
  { name: "Uninterrupted conversation — Dom gives full attention", category: "Quality Time", duration: "1 hour" },
  { name: "Scenic drive or walk — no phones", category: "Quality Time", duration: "1-2 hours" },
  { name: "Cook a meal together", category: "Quality Time", duration: "1-2 hours" },
  { name: "Board game or card game night", category: "Quality Time", duration: "2-3 hours" },
  { name: "Photo shoot together — fun and flirty", category: "Quality Time", duration: "1 hour" },
  { name: "Build a blanket fort and hide away", category: "Quality Time", duration: "1 evening" },
  { name: "Take a class together — art, cooking, dance", category: "Quality Time", duration: "1-2 hours" },
  { name: "Picnic in a park or scenic spot", category: "Quality Time", duration: "2-3 hours" },
  { name: "Video game co-op session", category: "Quality Time", duration: "2-3 hours" },
  { name: "Sunset or sunrise watching together", category: "Quality Time", duration: "30-60 min" },
  { name: "Dance together in the living room", category: "Quality Time", duration: "30 min" },
  { name: "Create a playlist together", category: "Quality Time", duration: "30-60 min" },
  { name: "Write love letters to each other", category: "Quality Time", duration: "30 min" },
  { name: "Couples journaling session", category: "Quality Time", duration: "30-45 min" },

  // Gifts & Treats Rewards
  { name: "Favorite snack or candy delivered", category: "Gifts & Treats", duration: "Instant" },
  { name: "New lingerie or outfit of their choice", category: "Gifts & Treats", duration: "Instant" },
  { name: "Coffee or tea made exactly how they like it", category: "Gifts & Treats", duration: "Instant" },
  { name: "Small surprise gift — under $20", category: "Gifts & Treats", duration: "Instant" },
  { name: "Favorite dessert — homemade or ordered", category: "Gifts & Treats", duration: "Instant" },
  { name: "Takeout from their favorite restaurant", category: "Gifts & Treats", duration: "1 meal" },
  { name: "New book or audiobook of their choice", category: "Gifts & Treats", duration: "Instant" },
  { name: "Wine, cocktail, or special drink prepared", category: "Gifts & Treats", duration: "Instant" },
  { name: "Upgrade to their favorite subscription for a month", category: "Gifts & Treats", duration: "1 month" },
  { name: "New toy or accessory for play", category: "Gifts & Treats", duration: "Instant" },
  { name: "Handwritten love note hidden for them to find", category: "Gifts & Treats", duration: "Instant" },
  { name: "Favorite candle or bath bomb", category: "Gifts & Treats", duration: "Instant" },
  { name: "Commission custom art of the two of you", category: "Gifts & Treats", duration: "Instant" },
  { name: "A piece of meaningful jewelry — collar charm, ring, bracelet", category: "Gifts & Treats", duration: "Instant" },
  { name: "Personalized playlist dedicated to them", category: "Gifts & Treats", duration: "Instant" },
  { name: "Gift card to their favorite store", category: "Gifts & Treats", duration: "Instant" },
  { name: "Surprise delivery at work or home", category: "Gifts & Treats", duration: "Instant" },

  // Power Exchange Rewards
  { name: "Role reversal for an evening — sub gets to be in charge", category: "Power Exchange", duration: "1 evening" },
  { name: "Dom kneels for them — symbolic acknowledgment", category: "Power Exchange", duration: "5 min" },
  { name: "Choose the scene — sub plans the entire session", category: "Power Exchange", duration: "1 session" },
  { name: "Dom follows one order without question", category: "Power Exchange", duration: "1 use" },
  { name: "Title upgrade — new pet name or honorific", category: "Power Exchange", duration: "Ongoing" },
  { name: "Collar ceremony — private re-collaring with words of affirmation", category: "Power Exchange", duration: "30 min" },
  { name: "Write a contract addendum together — sub suggests new terms", category: "Power Exchange", duration: "1 hour" },
  { name: "Dom wears something of sub's choosing", category: "Power Exchange", duration: "1 day" },
  { name: "Sub gets to 'punish' Dom playfully", category: "Power Exchange", duration: "1 session" },
  { name: "Special praise — Dom writes and reads a tribute to sub", category: "Power Exchange", duration: "15 min" },
  { name: "Dom performs an act of service for sub", category: "Power Exchange", duration: "1 task" },
  { name: "Negotiate one new soft limit to explore together", category: "Power Exchange", duration: "Discussion" },
  { name: "Sub chooses the safeword signal for the week", category: "Power Exchange", duration: "1 week" },
  { name: "Dom makes a vulnerable confession or admission", category: "Power Exchange", duration: "1 conversation" },
  { name: "Praise in front of others — public acknowledgment", category: "Power Exchange", duration: "Instant" },
  { name: "Sub helps write Dom's next task list", category: "Power Exchange", duration: "30 min" },
  { name: "Earn a permanent privilege — one rule permanently relaxed", category: "Power Exchange", duration: "Permanent" },

  // Sensory Rewards
  { name: "Feather tickling session — light and teasing", category: "Sensory", duration: "20-30 min" },
  { name: "Warm oil massage with ambient music", category: "Sensory", duration: "45-60 min" },
  { name: "Silk blindfold and whispered affirmations", category: "Sensory", duration: "20-30 min" },
  { name: "Ice and warm wax alternating — pleasure version", category: "Sensory", duration: "30 min" },
  { name: "ASMR-style head scratching and hair play", category: "Sensory", duration: "30 min" },
  { name: "Scented candle and music-filled relaxation", category: "Sensory", duration: "1 hour" },
  { name: "Trace patterns on their skin with fingertips", category: "Sensory", duration: "20 min" },
  { name: "Warm bath with essential oils together", category: "Sensory", duration: "45 min" },
  { name: "Silk or satin sheets for the night", category: "Sensory", duration: "1 night" },
  { name: "Gentle face touching and forehead kisses", category: "Sensory", duration: "15 min" },
  { name: "Weighted blanket and skin-to-skin contact", category: "Sensory", duration: "1 hour" },
  { name: "Soft music and slow dancing in candlelight", category: "Sensory", duration: "30 min" },
  { name: "Velvet or fur texture play on bare skin", category: "Sensory", duration: "20 min" },
  { name: "Warm compress on neck and shoulders", category: "Sensory", duration: "15 min" },
  { name: "Guided meditation together — Dom leads", category: "Sensory", duration: "20-30 min" },
  { name: "Sound bath or singing bowl session", category: "Sensory", duration: "30 min" },
  { name: "Gentle ear and neck kissing session", category: "Sensory", duration: "15-20 min" },

  // Intimacy Rewards
  { name: "Extended aftercare session — no rushing", category: "Intimacy", duration: "1+ hours" },
  { name: "Deep eye contact exercise — 5 minutes unbroken", category: "Intimacy", duration: "5-10 min" },
  { name: "Shower together — gentle and intimate", category: "Intimacy", duration: "30 min" },
  { name: "Fall asleep in each other's arms — no moving apart", category: "Intimacy", duration: "All night" },
  { name: "Skin-to-skin nap together", category: "Intimacy", duration: "1-2 hours" },
  { name: "Vulnerability exchange — share something new about each other", category: "Intimacy", duration: "30 min" },
  { name: "Recreate your first date or first scene", category: "Intimacy", duration: "1 evening" },
  { name: "Whispered declarations of love and ownership", category: "Intimacy", duration: "15 min" },
  { name: "Kiss for 10 minutes straight — nothing else", category: "Intimacy", duration: "10 min" },
  { name: "Body mapping — Dom traces and names every favorite spot", category: "Intimacy", duration: "30 min" },
  { name: "Wake up with gentle touches and sweet words", category: "Intimacy", duration: "1 morning" },
  { name: "Create a shared bucket list for the dynamic", category: "Intimacy", duration: "30-60 min" },
  { name: "Photo or video of the two of you — intimate keepsake", category: "Intimacy", duration: "15 min" },
  { name: "Dom verbally expresses pride in sub — detailed and specific", category: "Intimacy", duration: "10 min" },
  { name: "Read each other's journal entries together", category: "Intimacy", duration: "30 min" },
  { name: "Hold hands for an entire walk — no letting go", category: "Intimacy", duration: "30-60 min" },
  { name: "Write future promises to each other", category: "Intimacy", duration: "20-30 min" },
  { name: "Gratitude exchange — five things you love about each other", category: "Intimacy", duration: "15 min" },
];
